---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        LLDAP_JWT_SECRET: "{{ .lldap_jwt_secret }}"
        LLDAP_LDAP_USER_PASS: "{{ .lldap_ldap_user_pass }}"
        LLDAP_USER_DN: "{{ .lldap_user_dn }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .lldap_ldap_user_email }}"
        LLDAP_SERVER_KEY_SEED: "{{ .lldap_server_key_seed }}"
        LLDAP_DATABASE_URL: |-
          postgres://{{ .cnpg_lldap_user }}:{{ .cnpg_lldap_pass }}@postgres16-rw.database.svc.cluster.local/lldap
  dataFrom:
    - extract:
        key: lldap
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # db init
        INIT_POSTGRES_DBNAME: lldap
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .cnpg_lldap_user }}"
        INIT_POSTGRES_PASS: "{{ .cnpg_lldap_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .cnpg_super_pass }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
