---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Deploy key
        GH_DEPLOY_KEY: "{{ .hassio_github_deploy_key }}"
        # Home-Assistant
        SECRET_INTERNAL_URL: http://172.16.13.21:8123
        SECRET_INTERNAL_URL_DIRECT: http://172.16.13.21:8123
        SECRET_EXTERNAL_URL: https://${HOSTNAME}
        SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16
        # Home-Assistant Zones
        SECRET_ZONE_HOME_ELEVATION: "{{ .hassio_zone_home_elevation }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .hassio_zone_home_latitude }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .hassio_zone_home_longitude }}"
        # Postgres DB
        POSTGRES_DB: &dbname homeassistant
        POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .hassio_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .hassio_postgres_pass }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: hassio
    - extract:
        key: crunchydata
