---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom:
              - secretRef:
                  name: home-assistant-secret

        pod:
          labels:
            ingress.home.arpa/nginx-external: allow
            egress.home.arpa/world: allow
            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["172.16.13.21/24"]
              }]

        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.2.2
            env:
              HASS_UNIT_SYSTEM: metric
              HASS_TRUSTED_PROXIES: "10.244.0.0/16"
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
                memory: 1254M
              limits:
                memory: 1254M

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        className: "external-nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: ingress-ext.monosense.io
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: tls-hassio
            hosts:
              - "${HOSTNAME}"

    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        globalMounts:
          - path: /root/.ssh/id_rsa
            subPath: GH_DEPLOY_KEY
