---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-iscsi-hdd-secret
  namespace: system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-iscsi
          httpConnection:
            protocol: http
            host: "172.16.11.1"
            port: "80"
            apiKey: {{ .dcsi_truenas_api_key }}
            allowInsecure: true
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: hdd/k8s/vols
            detachedSnapshotsDatasetParentName: hdd/k8s/snapshots
            zvolCompression: gzip
            zvolDedup: false
            zvolEnableReservation: false
            zvolBlocksize: 16K
          iscsi:
            targetPortal: "172.16.11.1:3260"
            targetGroups:
              - targetGroupPortalGroup: 1
                targetGroupInitiatorGroup: 1
                targetGroupAuthType: None
            namePrefix: ""
            nameSuffix: ""
            extentInsecureTpc: true
            extentXenCompat: false
            extentDisablePhysicalBlocksize: true
            extentBlocksize: 512
            extentRpm: "7200"
            extentAvailThreshold: 0
  dataFrom:
    - extract:
        key: dcsi
