---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secretName harbor-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secretName
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Harbor
        password: "{{ .harbor_postgres_pass }}"
        HARBOR_ADMIN_PASSWORD: "{{ .harbor_admin_pass }}"
        # Postgres DB
        POSTGRES_DB: &dbname registry
        POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .harbor_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .harbor_postgres_pass }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: harbor
    - extract:
        key: crunchydata
