---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname frigate-secrets
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FRIGATE_RTSP_USERNAME: "{{ .frigate_rtsp_user }}"
        FRIGATE_RTSP_PASSWORD: "{{ .frigate_rtsp_pass }}"
        FRIGATE_MQTT_USERNAME: "{{ .frigate_mqtt_user }}"
        FRIGATE_MQTT_PASSWORD: "{{ .frigate_mqtt_pass }}"
  dataFrom:
    - extract:
        key: frigate
