---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname redis
  namespace: flux-system
spec:
  path: ./kubernetes/prod/apps/database/redis/app
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  sourceRef:
    kind: GitRepository
    name: production
  prune: true
  wait: true
  interval: 10m
