---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline-secret
    template:
      data:
        # App S3
        AWS_REGION: dpk-ptr-tcore-1
        AWS_S3_ACL: private
        AWS_S3_FORCE_PATH_STYLE: "true"
        AWS_S3_UPLOAD_BUCKET_NAME: "outline"
        AWS_S3_UPLOAD_BUCKET_URL: "https://s3.monosense.io:9000/"
        FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"
        AWS_ACCESS_KEY_ID: "{{ .outline_s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .outline_s3_secret_key }}"
        # OIDC
        OIDC_AUTH_URI: "https://auth.monosense.io/application/o/authorize/"
        OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        OIDC_DISPLAY_NAME: SSO
        OIDC_SCOPES: "openid profile email"
        OIDC_TOKEN_URI: "https://auth.monosense.io/application/o/token/"
        OIDC_USERINFO_URI: "https://auth.monosense.io/application/o/userinfo/"
        OIDC_USERNAME_CLAIM: email
        SECRET_KEY: "{{ .outline_secret_key }}"
        UTILS_SECRET: "{{ .outline_utils_secret }}"
        DATABASE_URL: "postgres://{{ .outline_postgres_user }}:{{ .outline_postgres_pass }}@postgres-rw.database.svc.cluster.local/outline"
        # SMTP
        SMTP_HOST: "{{ .zohomail_smtp_host }}"
        SMTP_PORT: "{{ .zohomail_smtp_port }}"
        SMTP_USERNAME: "{{ .zohomail_email_address }}"
        SMTP_PASSWORD: "{{ .zohomail_smtp_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: outline
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .outline_postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .outline_postgres_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: outline
    - extract:
        key: crunchydata
    - extract:
        key: zohomail
