---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name cloudnative-pg-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: crunchydata
        property: crunchy_super_user
    - secretKey: password
      remoteRef:
        key: crunchydata
        property: crunchy_super_pass
    - secretKey: s3-access-key
      remoteRef:
        key: crunchydata
        property: crunchy_s3_access_key
    - secretKey: s3-secret-key
      remoteRef:
        key: crunchydata
        property: crunchy_s3_secret_key
