---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./cluster-gitlab.yaml
  - ./cluster-immich.yaml
  - ./externalsecret.yaml
  - ./service.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
