---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .api_token }}"
        POSTGRES_DB: &dbname authentik
        POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .authentik_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .authentik_postgres_pass }}"
        REDIS_PASS: "{{ .authentik_redis_pass }}"
        SMTP_HOST: "{{ .zohomail_smtp_host }}"
        SMTP_PORT: "{{ .zohomail_smtp_port }}"
        SMTP_USERNAME: "{{ .zohomail_email_address }}"
        SMTP_PASS: "{{ .zohomail_smtp_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: crunchydata
    - extract:
        key: zohomail
