---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonar-oss
spec:
  chart:
    spec:
      chart: sonarqube
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: sonarqube
      tag: 10.4.1-community

    deployment: true

    podSecurityContext:
      fsGroup: 1000

    securityContext:
      runAsGroup: 0
      runAsUser: 1000

    livenessProbe:
      httpGet:
        path: /api/system/status
        port: http
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 10
      timeoutSeconds: 1

    readinessProbe:
      httpGet:
        path: /api/system/status
        port: http
      initialDelaySeconds: 60
      periodSeconds: 30
      failureThreshold: 10
      timeoutSeconds: 1

    service:
      type: ClusterIP
      port: 9000

    ingress:
      enabled: true
      ingressClassName: internal-nginx
      hosts:
        - &hostname sonarqube.monosense.io
      tls:
        - hosts:
            - *hostname

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: ceph-block
      size: 15Gi

    resources:
      requests:
        cpu: 512m
        memory: 1024Mi
      limits:
        cpu: 1000m
        memory: 4096Mi

    extraInitContainers: []

    psql:
      host: postgres-rw.database.svc.cluster.local
      port: 5432
      database: sonarqube
      username: sonarqube
      password:
        secret: sonarqube-secret
        key: dbpass
