---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name blocky
spec:
  staticConfigs:
    - targets:
        - 172.16.16.9:4000
  metricsPath: /metrics
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
