---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name homeassistant
spec:
  staticConfigs: [targets: ["172.16.13.21:8123"]]
  metricsPath: /api/prometheus
  honorTimestamps: true
  authorization:
    type: Bearer
    credentials:
      key: HASSIO_TOKEN
      name: hass-ll-token
      optional: false
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
