---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-k8s-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 30m

  values:
    runnerScaleSetName: arc-runner-set-k8s-cluster

    githubConfigUrl: https://github.com/trosvald/k8s-cluster

    minRunners: 1
    maxRunners: 3

    containerMode:
      type: "dind"

    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: dev

    listenerTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: arc-k8s-cluster-listener
          egress.home.arpa/world: allow
          egress.home.arpa/apiserver: allow
          egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
      spec:
        containers: []

    template:
      metadata:
        labels:
          app.kubernetes.io/name: arc-k8s-cluster-runner
          egress.home.arpa/world: allow
          egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.314.1@sha256:338d851a66c4942f7a33d4dc3d0ff1459e05e31e258153242521e9f8e4c64dd7
            command: ["/home/runner/run.sh"]

  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key
