---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/prod/apps/database/pgadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: pgadmin
      namespace: database
  interval: 30m
  wait: true
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: "pgadmin.monosense.io"
      APP_UID: "5050"
      APP_GID: "5050"
      VOLSYNC_CLAIM: pgadmin-data
      VOLSYNC_CAPACITY: 2Gi
