---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cloudflared/ks.yaml
  # - ./echo-server/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./multus/ks.yaml
  # Standard Resources
  - ./s3-proxy/ks.yaml
  - ./chat-proxy/ks.yaml
  - ./hassio-proxy/ks.yaml
  # - ./gitlab-proxy/ks.yaml
