---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
  namespace: media
spec:
  storageClassName: immich-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "172.16.11.1"
    path: /mnt/hdd/nfs/immich
  # Note: The first two options are strictly for NFSv4.2
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Ti
