---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-nfs
  resources:
    requests:
      storage: 2Ti
