---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GATUS_TELEGRAM_BOT_TOKEN: "{{ .telegram_bot_token }}"
        GATUS_TELEGRAM_CHANNEL_ID: "{{ .telegram_channel_id }}"
        POSTGRES_DB: &dbname gatus
        POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .gatus_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .gatus_postgres_pass }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: crunchydata
    - extract:
        key: gatus
    - extract:
        key: telegram
