---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: "{{ .zigbee_config_advanced_ext_pan_id }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: "{{ .zigbee_config_advanced_pan_id }}"
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: "{{ .zigbee_config_advanced_network_key }}"
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .zigbee_mqtt_user }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .zigbee_mqtt_pass }}"
  dataFrom:
    - extract:
        key: zigbee
