---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-device
spec:
  rules:
    - # Sonoff Zigbee USB Dongle
      name: zigbee
      labels:
        feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["ff"] }
            vendor: { op: In, value: ["10c4"] }
            device: { op: In, value: ["ea60"] }
