---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-iscsi-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: zfs-generic-iscsi
          sshConnection:
            host: {{ .dcsi_host_address }}
            port: {{ .dcsi_ssh_port }}
            username: {{ .dcsi_ssh_user }}
            password: {{ .dcsi_ssh_password }}
          zfs:
            cli:
              paths:
                zfs: /usr/sbin/zfs
                zpool: /usr/sbin/zpool
                sudo: /usr/bin/sudo
                chroot: /usr/sbin/chroot
            datasetParentName: pool1/k8s/vols
            detachedSnapshotsDatasetParentName: pool1/k8s/snaps
            zvolCompression:
            zvolDedup:
            zvolEnableReservation: false
            zvolBlocksize:
          iscsi:
            shareStrategy: "targetCli"
            shareStrategyTargetCli:
              #sudoEnabled: true
              basename: {{ .dcsi_basename }}
              tpg:
                attributes:
                  authentication: 0
                  generate_node_acls: 1
                  cache_dynamic_acls: 1
                  demo_mode_write_protect: 0
              auth:
            targetPortal: {{ .dcsi_target_portal }}
            interface: ""
            namePrefix: ""
            nameSuffix: ""

  dataFrom:
    - extract:
        key: dcsi
