---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname reflector
  namespace: flux-system
spec:
  path: ./kubernetes/prod/apps/kube-system/reflector/app
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: production
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  prune: true
  wait: false
  interval: 10m
