---
mqtt:
  host: mattermost.monosense.io
  topic_prefix: frigate
  user: "{{ .frigate_mqtt_user }}"
  password: "{{ .frigate_mqtt_pass }}"

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "info"]
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  coral:
    type: edgetpu
    device: usb

logger:
  default: info

database:
  path: /data/frigate.db

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
record:
  enabled: true
  retain:
    days: 8
    mode: all
  events:
    pre_capture: 5
    post_capture: 5
    objects:
      - person
      - car
      - motorcycle
      - bicycle
    required_zones: []
    retain:
      default: 8
      mode: active_objects
      objects:
        person: 30
        car: 30
        motorcycle: 30

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  crop: false
  required_zones: []
  retain:
    default: 8
    objects:
      person: 30

go2rtc:
  streams:
    ipc01:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@172.16.14.101:554/cam/realmonitor?channel=1?subtype=0
    ipc01_substream:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@172.16.14.101:554/cam/realmonitor?channel=1?subtype=1
    ipc02:
      - rtsp:/admin:{FRIGATE_RTSP_PASSWORD}@172.16.14.102:554/cam/realmonitor?channel=1?subtype=0
    ipc02_substream:
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@i72.16.14.102:554/cam/realmonitor?channel=1?subtype=1
    # ipc03:
    #   - rtsp://admin:{FRIGATE_RTSP_PASSWORD}ipc03.monosense.io:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    # ipc03_substream:
    #   - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@ipc03.monosense.io:554/cam/realmonitor?channel=1?subtype=0

cameras:
  ipc01:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/ipc01
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/ipc01
          input_args: preset-rtsp-restream
          roles:
            - detect
    detect:
      fps: 15
      width: 1920
      height: 1080

  # ipc02:
  #   ffmpeg:
  #     output_args:
  #       record: preset-record-generic-audio-copy
  #     inputs:
  #       - path: rtsp://127.0.0.1:8554/ipc02
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - record
  #       - path: rtsp://127.0.0.1:8554/ipc02_substream
  #         input_args: preset-rtsp-restream
  #         roles:
  #           - detect
  #   detect:
  #     fps: 10
  #     width: 704
  #     height: 480
