---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/managed-by: Helm
fieldSpecs:
  - path: metadata/labels
    create: true
---
apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: annotations
annotations:
  meta.helm.sh/release-name: immich-pg
  meta.helm.sh/release-namespace: media
fieldSpecs:
  - path: metadata/annotations
    create: true
