---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
spec:
  endpoints:
    - dnsName: ingress-ext.monosense.io
      recordType: CNAME
      targets: ["31bc8e34-883f-4225-94af-2989ef513027.cfargotunnel.com"]
