---
ingress:
  - hostname: "monosense.io"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.monosense.io
  - hostname: "*.monosense.io"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.monosense.io
  - service: http_status:404
