---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: guarded
        url: 203.142.82.222
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "${GATUS_SUBDOMAIN:-${APP}}.monosense.io"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover