---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        PGADMIN_DEFAULT_EMAIL: "{{ .pgadmin_default_email }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: pgadmin
    - extract:
        key: crunchydata
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-oidc
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin-oidc-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: pgadmin-config-local-tpl
            items:
              - key: config_local.py
  dataFrom:
    - extract:
        key: pgadmin
        property: oidc_client_id
    - extract:
        key: pgadmin
        property: oidc_client_secret
