---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: &app pgadmin
  app.kubernetes.io/instance: *app
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../../templates/volsync
configMapGenerator:
  - name: pgadmin-config-local-tpl
    files:
      - ./config/config_local.py
  - name: servers-json
    files:
      - config/servers.json
generatorOptions:
  disableNameSuffixHash: true
