---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname excalidraw
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/prod/apps/selfhosted/excalidraw/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: false
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: draw.monosense.io
