---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-cctv
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-cctv",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth1.1614",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "0.0.0.0/0", "gw": "172.16.14.254" }
            ]
          }
        }
      ]
    }
