---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth1.1613",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "172.16.10.0/24", "gw": "172.16.13.254" },
              { "dst": "172.16.11.0/24", "gw": "172.16.13.254" },
              { "dst": "172.16.12.0/24", "gw": "172.16.13.254" },
              { "dst": "172.16.13.0/24", "gw": "172.16.13.254" },
              { "dst": "172.16.14.0/24", "gw": "172.16.13.254" },
              { "dst": "172.16.16.0/24", "gw": "172.16.13.254" }
            ]
          }
        }
      ]
    }
