---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  targetNamespace: flux-system
  path: ./kubernetes/prod/apps/flux-system/add-ons/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  targetNamespace: flux-system
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/prod/apps/flux-system/add-ons/notifications
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhooks
  namespace: flux-system
spec:
  targetNamespace: flux-system
  dependsOn:
    - name: external-secrets-stores
  path: ./kubernetes/prod/apps/flux-system/add-ons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
