---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name dcsi-nfs-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: zfs-generic-nfs
          sshConnection:
            host: {{ .dcsi_host_address }}
            port: {{ .dcsi_ssh_port }}
            username: {{ .dcsi_ssh_user }}
            password: {{ .dsci_ssh_password }}
          zfs:
            cli:
              paths:
                zfs: /usr/sbin/zfs
                zpool: /usr/sbin/zpool
                sudo: /usr/bin/sudo
                chroot: /usr/sbin/chroot
            datasetParentName: pool1/k8s/vols
            detachedSnapshotsDatasetParentName: pool1/k8s/snaps
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareStrategy: "setDatasetProperties"
            setDatasetProperties:
              properties:
                sharenfs: "rw,no_subtree_check,no_root_squash"
                #sharenfs: "on"
                #share: ""
            shareHost: {{ .dcsi_host_address }}
  dataFrom:
    - extract:
        key: dcsi
