---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  sourceRef:
    kind: GitRepository
    name: production
  interval: 10m
  path: "./kubernetes/prod/apps/monitoring/grafana/app"
  prune: true
  wait: false
  dependsOn:
    - name: kube-prometheus-stack
    - name: external-secrets-stores
    - name: cloudnative-pg-cluster
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: grafana.monosense.io
      AUTH_HOSTNAME: auth.monosense.io
