---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mqtt-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ADMIN_PASSWORD: "{{ .mqtt_admin_password }}"
        MQTT_USER: "{{ .mqtt_user }}"
        MQTT_PASS: "{{ .mqtt_pass }}"

  dataFrom:
    - extract:
        key: mqtt
