---
data_dir: /vector-data-dir
api:
  enabled: true
  address: 0.0.0.0:8686

#
# Sources
#

sources:
  journald_source:
    type: vector
    version: "2"
    address: 0.0.0.0:6000

  talos_kernel_logs:
    address: 0.0.0.0:6001
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host

  talos_service_logs:
    address: 0.0.0.0:6002
    type: socket
    mode: udp
    max_length: 102400
    decoding:
      codec: json
    host_key: __host

  kubernetes_source:
    type: vector
    version: "2"
    address: 0.0.0.0:6010

#
# Transforms
#

transforms:
  talos_kernel_transform:
    type: remap
    inputs: ["talos_kernel_logs"]
    source: |-
      r1 = replace!(.__host, "172.16.11.3", "p-tlx-k8s-m0")
      r2 = replace(r1, "172.16.11.4", "p-tlx-k8s-m1")
      r3 = replace(r2, "172.16.11.5", "p-tlx-k8s-m2")
      r4 = replace(r3, "172.16.11.6", "p-tlx-k8s-w0")
      r5 = replace(r4, "172.16.11.7", "p-tlx-k8s-w1")
      r6 = replace(r5, "172.16.11.8", "p-tlx-k8s-w2")
      .node = r6

  talos_service_transform:
    type: remap
    inputs: ["talos_service_logs"]
    source: |-
      r1 = replace!(.__host, "172.16.11.3", "p-tlx-k8s-m0")
      r2 = replace(r1, "172.16.11.4", "p-tlx-k8s-m1")
      r3 = replace(r2, "172.16.11.5", "p-tlx-k8s-m2")
      r4 = replace(r3, "172.16.11.6", "p-tlx-k8s-w0")
      r5 = replace(r4, "172.16.11.7", "p-tlx-k8s-w1")
      r6 = replace(r5, "172.16.11.8", "p-tlx-k8s-w2")
      r7 = replace(r6, r'172.16.11.*', "talos")
      .node = r7

  kubernetes_remap:
    type: remap
    inputs: ["kubernetes_source"]
    source: |-
      # Standardize 'app' index
      .custom_app_name = .pod_labels."app.kubernetes.io/name" || .pod_labels.app || .pod_labels."k8s-app" || "unknown"
      # Drop pod_labels
      del(.pod_labels)

#
# Sinks
#

sinks:
  journald:
    inputs: ["journald_source"]
    type: loki
    endpoint: http://loki-gateway.observability.svc.cluster.local
    encoding: { codec: json }
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      hostname: '{{ host }}'

  talos_kernel:
    type: loki
    inputs: ["talos_kernel_transform"]
    endpoint: http://loki-gateway.observability.svc.cluster.local
    encoding:
      codec: json
      except_fields:
        - __host
    batch:
      max_bytes: 524288
    out_of_order_action: rewrite_timestamp
    labels:
      node: "{{ node }}"
      facility: "{{ facility }}"
      namespace: "talos:kernel"

  talos_service:
    type: loki
    inputs: ["talos_service_transform"]
    endpoint: http://loki-gateway.observability.svc.cluster.local
    encoding:
      codec: json
      except_fields:
        - __host
    batch:
      max_bytes: 524288
    out_of_order_action: rewrite_timestamp
    labels:
      node: "{{ node }}"
      talos_service: '{{ "talos:service "}}'
      namespace: "talos:service"

  kubernetes:
    inputs: ["kubernetes_remap"]
    type: loki
    endpoint: http://loki-gateway.observability.svc.cluster.local
    encoding: { codec: json }
    out_of_order_action: accept
    remove_label_fields: true
    remove_timestamp: true
    labels:
      app: '{{ custom_app_name }}'
      namespace: '{{ kubernetes.pod_namespace }}'
      node: '{{ kubernetes.pod_node_name }}'
