---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-minio
spec:
  interval: 12h
  approvePlan: "auto"
  backendConfig:
    disable: true
  cliConfigSecretRef:
    name: tfe-cli-config
  path: ./infrastructure/terraform/minio
  sourceRef:
    kind: GitRepository
    name: production
    namespace: flux-system
  runnerPodTemplate:
    spec:
      env:
        - name: OP_CONNECT_HOST
          value: http://onepassword-connect.monosense.io:8080
        - name: OP_CONNECT_TOKEN
          valueFrom:
            secretKeyRef:
              name: tf-controller-secrets
              key: OP_CONNECT_TOKEN
      volumeMounts:
        - name: tf-controller-sops-key
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: keys.txt
      volumes:
        - name: tf-controller-sops-key
          secret:
            secretName: tf-controller-sops-key
