---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: postgres16-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: &dbUser "{{ .cnpg_grafana_user }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .cnpg_grafana_pass }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .grafana_oidc_client_secret }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .cnpg_super_pass }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: cloudnative-pg
