---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname authentik
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/prod/apps/security/authentik/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: true
  dependsOn:
    - name: external-secrets-stores
    - name: cloudnative-pg-cluster
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: auth.monosense.io
