---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname outline
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/prod/apps/selfhosted/outline/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: false
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: docs.monosense.io
