---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Grafana App
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .grafana_oidc_client_secret }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .grafana_oidc_client_id }}"
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_HOST: &dbhost postgres-rw.database.svc.cluster.local
        GF_DATABASE_USER: &dbuser "{{ .grafana_postgres_user }}"
        GF_DATABASE_PASSWORD: &dbpass "{{ .grafana_postgres_pass }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: crunchydata
