---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_REGION: "{{ .minio_region }}"
        S3_HOST: "{{ .minio_server }}"
        S3_ACCESS_KEY: "{{ .thanos_s3_access_key }}"
        S3_SECRET_KEY: "{{ .thanos_s3_secret_key }}"
        S3_BUCKET: "{{ .thanos_s3_bucket }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: thanos
