---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname weave-gitops
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/prod/apps/flux-system/weave-gitops/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: false
  dependsOn:
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: gitops.monosense.io
