---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname mqtt
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/prod/apps/home-automation/mqtt/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: production
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: mqtt.monosense.io
