---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./libreddit/ks.yaml
  # - ./miniflux/ks.yaml
  # - ./node-red/ks.yaml
  # - ./wallabag/ks.yaml
  # - ./zipline/ks.yaml
