---
apiVersion: v1
kind: Service
metadata:
  name: ${APP}
spec:
  externalName: hassio.monosense.io
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
  type: ExternalName
