---
global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  repeat_interval: 12h
  receiver: mattermost

  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: mattermost
      continue: true
      matchers:
        - severity = "critical"

inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"

receivers:
  - name: "null"
  - name: mattermost
    webhook_configs:
      - send_resolved: true
        url: "https://chat.monosense.io/plugins/alertmanager/api/webhook?token='{{ .mattermost_token }}'"
