---
global:
  resolve_timeout: 5m
  slack_api_url: "{{ .slack_hook }}"

route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  repeat_interval: 12h
  receiver: slack

  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: slack
      continue: true
      matchers:
        - severity = "critical"

inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"

receivers:
  - name: "null"
  - name: slack
    slack_configs:
      - channel: "#gitops"
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        color: '{{ if eq .Status "firing" -}}{{ if eq .CommonLabels.severity "warning" -}}warning{{- else if eq .CommonLabels.severity "critical" -}}danger{{- else -}}#439FE0{{- end -}}{{ else -}}good{{- end }}'
templates: [/etc/alertmanager/config/*.tmpl]
