apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:azvn3Hy3O82yRfdfOTqZKG+czJOgsYl8kxghiU03siOZlL6cJZ1QBT73Qdnnfs7pk1J3aC2Lu0ZmYtfO26+UPpBJoSohKZsCTF+Q35gj4ypca1TSiXm9VT5Tn3qp1nHuELOiwazbmSr9F6gxxRxevckry6PgrWXRJ8YKZCEVAjT9vEqUBMDjeXF5BQhqN8YMqgF4k8ZSaW8nrw8ey85Qxo5euY5KMerkZLhhiGR8p1hTXcsUavkxwRhO8VP6cM0Q5s+r6pULEw1gbgyl2fso51L8HBv0LUfxwgG0vu5wTvW/0DO7hiwnVhy2JhMkiS80YynkgYEbQiwBjSz9Ldq8cxeZixhoKt+jbmoKTU/95B0dCw1CdwWT6P40Q/cqYgg+Gy0HkSKEYZbVU9BIuGOOBO93HKMs2OZfDMsEG09k7uAA8bZ0GHQS7Rf811Lszzn7AqDpjkCtkhqKL7oXPLe8Y5za7EEwqNqUXGWE0pj4KG68UBGIPy08BbsnhwCnlpGdBc4Qes8k7ZWrH+8lLB+er7sT1GkV8Vsog+WNP69F/x3D+yx59aWwmIaSolv27tpiu8q2A2YHVhcynbhu4UV7+AYDt4Lj2Nro6RORw2KBVJLtxSmzKem8TbD0JXTi6JlB+rtdMra6/phfMCD+4Xez/J7nMru18d1LN+igO9PREFXzI7Kkt5V7lMYGec4rALRMabWBzva13E4GiOTVW+6Yt2ZgAEuykwXBB6FbFxK9X0V1hd4y+ZK6iU8WchdCqZ3l88T2q4ohkdhdEnLAFN0BoWaj8LtQzTOsAsh502y0sY4SvgQ7zjTq5ftt7PYyTljbHP3dtbkmJTdb739FiU5c3TUJ,iv:RS7owP25g9ws0/CK+tVZKMUz+hk1e07ArEwNjNyutOA=,tag:njtsmTP7MebjMgI/gKrxuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j3hsfptdfsfwvkf504etjkrtmajny9csrfh5s24uqh6fchmg5dgqg087ek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VDl5REw1dVV5bkxFZVNj
            TGh4WitxS29TOXBpZlhvbTk5d1ZQT3YyYXpFCnZyYmwxTFA5bjBRYzAwOFNRdUVy
            MElRbjFUN0k4TWJQTlFZaDVMdGt6blEKLS0tIG5HVmhSTVhLQnQ2eWpUOEJFWlBZ
            OHdSRytDNUZUVXNsZjQ5TFFYU2JFYmMKXFZTCJW2c7r0P9oc3KaiaLnrkScDhH85
            s66L7k2XlS7dtRflvp97odO+0kUAcd9K/eUzid4pvYQ6fAPk7ZB6FA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-15T16:38:34Z"
    mac: ENC[AES256_GCM,data:Dg70yelZGlS4UbMseZ6Ooak3guNW75Bye6YWFHfd83JryMmTeuGwgxEUUImXk4n4WZxXP+EzaKgz/lfScexwkVJQWDvltBPMwY7ssIy5RqVgoaBHW+/h25O3DzP3ZP+I/PVPx+H94hqKiQLwoKD6Yhr8lw2RkBuHmgmcuD+m+Xg=,iv:4i5nMXz9VKyMVFNqvx9QuFXN8uQ7aXbc+Uv1xo5cyHU=,tag:e7aDwR9bP4lbbs+j58oq6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
