---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-cluster-user-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cluster-user-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ .weave_gitops_admin_password }}"
  dataFrom:
    - extract:
        key: weave-gitops
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-oidc-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oidc-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        clientID: "{{ .oidc_client_id }}"
        clientSecret: "{{ .oidc_client_secret }}"
        issuerURL: https://auth.monosense.io/application/o/authorize/
        redirectURL: https://gitops.monosense.io/oauth2/callback
        customScopes: openid,profile,email,groups
        claimGroups: groups
        claimUsername: preferred_username
  dataFrom:
    - extract:
        key: weave-gitops
