---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  interval: 30m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.36
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: cluster-user-auth

    logLevel: info

    adminUser:
      create: true
      createSecret: false
      username: admin

    networkPolicy:
      create: false

    metrics:
      enabled: true

    rbac:
      create: true
      additionalRules:
        - apiGroups:
            - "infra.contrib.fluxcd.io"
          resources:
            - "terraforms"
          verbs:
            - "get"
            - "list"
            - "patch"

    ingress:
      enabled: true
      className: internal-nginx
      annotations:
        nginx.ingress.kubernetes.io/custom-http-errors: "418"
      hosts:
        - host: "${HOSTNAME}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "${HOSTNAME}"
