---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.13
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    installCRDs: true
    replicaCount: 3
    leaderElect: true
    grafana:
      enabled: true
    serviceMonitor:
      enabled: true
      interval: 1m
    backgroundController:
      serviceMonitor:
        enabled: true
        interval: 1m
    cleanupController:
      serviceMonitor:
        enabled: true
        interval: 1m
    reportsController:
      serviceMonitor:
        enabled: true
        interval: 1m
    webhook:
      serviceMonitor:
        enabled: true
        interval: 1m
    certController:
      serviceMonitor:
        enabled: true
        interval: 1m
