---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app excalidraw
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/excalidraw
              tag: latest@sha256:bafe3a1e529aac9e9d536199e77133b60bfce4413458ee0a46e48fb07095d23b
            resources:
              requests:
                cpu: 5m
                memory: 100M
              limits:
                memory: 128M
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                a pp.kubernetes.io/name: *app
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: internal-nginx
        hosts:
          - host: ${HOSTNAME}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - ${HOSTNAME}
