---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name talos-s3-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_REGION: dpk-ptr-tcore-1
        CUSTOM_S3_ENDPOINT: https://s3.monosense.io:9000
        AWS_ACCESS_KEY_ID: "{{ .talos_s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .talos_s3_secret_key }}"
        BUCKET: talos
        CLUSTER_NAME: prod
        S3_PREFIX: backups
        AGE_X25519_PUBLIC_KEY: "{{ .talos_age_public_key }}"
  dataFrom:
    - extract:
        key: talos
