---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
spec:
  instances: 3
  imageName: ghcr.io/bo0tzz/cnpgvecto.rs:16.1-v0.1.11
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: ceph-block
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      synchronous_commit: "off"
      shared_buffers: 512MB
    shared_preload_libraries:
      - "vectors.so"
  superuserSecret:
    name: immich-pg-secret
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 4Gi
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://crunchydata/
      endpointURL: https://s3.monosense.io:9000
      serverName: immich
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: s3-access-key
        secretAccessKey:
          name: cloudnative-pg-secret
          key: s3-secret-key
