---
apiVersion: v1
kind: Service
metadata:
  name: &app immich-db
  namespace: media
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: immich.monosense.io
    io.cilium/lb-ipam-ips: 10.10.10.6
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: immich
    role: primary
