---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chat-proxy
  namespace: flux-system
spec:
  path: ./kubernetes/prod/apps/network/chat-proxy/app
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: production
  commonMetadata:
    labels:
      app.kubernetes.io/name: &appname chat-proxy
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: chat.monosense.io
