---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-backups
  namespace: media
spec:
  storageClassName: immich-postgres-backups
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.11.1
    path: "/mnt/hdd/nfs/backup"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-backups
  namespace: media
spec:
  storageClassName: immich-postgres-backups
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
