---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-backup
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-postgres-backups-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .crunchy_super_user }}"
        POSTGRES_PASSWORD: "{{ .crunchy_super_pass }}"
  dataFrom:
    - extract:
        key: crunchydata
