---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_NAME: "{{ .thanos_s3_bucket }}"
        S3_BUCKET_HOST: "{{ .minio_server }}"
        S3_BUCKET_REGION: "{{ .minio_region }}"
        S3_ACCESS_KEY: "{{ .thanos_s3_access_key }}"
        S3_SECRET_KEY: "{{ .thanos_s3_secret_key }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: thanos
