---
name: "Meta: Sync labels"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    # runs-on: arc-runner-set-k8s-cluster
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.TROSVALD_APP_ID }}"
          private-key: "${{ secrets.TROSVALD_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          token: "${{ steps.app-token.outputs.token }}"
          delete-other-labels: true
