---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gitlab-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: &dbname gitlab
        POSTGRES_HOST: &dbhost postgres-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .gitlab_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .gitlab_postgres_pass }}"
        SMTP_PORT: "{{ .zohomail_smtp_port }}"
        SMTP_SERVER: "{{ .zohomail_smtp_host }}"
        SMTP_USERNAME: "{{ .zohomail_email_address }}"
        SMTP_PASS: "{{ .zohomail_smtp_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
        INITIAL_ROOT_PASSWORD: "{{ .gitlab_root_password }}"

  dataFrom:
    - extract:
        key: gitlab
    - extract:
        key: crunchydata
    - extract:
        key: zohomail
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-runner-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-registration-token: "{{ .gitlab_runner_registration_token }}"
        runner-token: "{{ .gitlab_runner_token }}"
  dataFrom:
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-saml-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        runner-registration-token: "{{ .authentik_idp_cert_fingerprint }}"
        runner-token: "{{ .gitlab_runner_token }}"
  dataFrom:
    - extract:
        key: gitlab
