---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gitlab-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: &dbname gitlab
        POSTGRES_HOST: &dbhost pggitlab-rw.database.svc.cluster.local
        POSTGRES_USER: &dbuser "{{ .gitlab_postgres_user }}"
        POSTGRES_PASS: &dbpass "{{ .gitlab_postgres_pass }}"
        SMTP_PORT: "{{ .zohomail_smtp_port }}"
        SMTP_SERVER: "{{ .zohomail_smtp_host }}"
        SMTP_USERNAME: "{{ .zohomail_email_address }}"
        SMTP_PASS: "{{ .zohomail_smtp_password }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .crunchy_super_pass }}"
        INITIAL_ROOT_PASSWORD: "{{ .gitlab_root_password }}"

  dataFrom:
    - extract:
        key: gitlab
    - extract:
        key: crunchydata
    - extract:
        key: zohomail
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-rail-storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: |
          provider: AWS
          region: "{{ .gitlab_s3_region }}"
          aws_access_key_id: "{{ .gitlab_rail_s3_access_key }}"
          aws_secret_access_key: "{{ .gitlab_rail_s3_secret_key}}"
          aws_signature_version: 4
          host: s3.monosense.io
          endpoint: "https://s3.monosense.io:9000"
          path_style: true
  dataFrom:
    - extract:
        key: gitlab-rail
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-artifacts-storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: |
          provider: AWS
          region: "{{ .gitlab_s3_region }}"
          aws_access_key_id: "{{ .gitlab_artifacts_s3_access_key }}"
          aws_secret_access_key: "{{ .gitlab_artifacts_s3_secret_key}}"
          aws_signature_version: 4
          host: s3.monosense.io
          endpoint: "https://s3.monosense.io:9000"
          path_style: true
  dataFrom:
    - extract:
        key: gitlab-artifacts
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-uploads-storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: |
          provider: AWS
          region: "{{ .gitlab_s3_region }}"
          aws_access_key_id: "{{ .gitlab_uploads_s3_access_key }}"
          aws_secret_access_key: "{{ .gitlab_uploads_s3_secret_key}}"
          aws_signature_version: 4
          host: s3.monosense.io
          endpoint: "https://s3.monosense.io:9000"
          path_style: true
  dataFrom:
    - extract:
        key: gitlab-uploads
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-packages-storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: |
          provider: AWS
          region: "{{ .gitlab_s3_region }}"
          aws_access_key_id: "{{ .gitlab_packages_s3_access_key }}"
          aws_secret_access_key: "{{ .gitlab_packages_s3_secret_key}}"
          aws_signature_version: 4
          host: s3.monosense.io
          endpoint: "https://s3.monosense.io:9000"
          path_style: true
  dataFrom:
    - extract:
        key: gitlab-packages
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-registry-storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          s3:
            v4auth: true
            regionendpoint: "https://s3.monosense.io:9000"
            pathstyle: true
            region: "{{ .gitlab_s3_region }}"
            bucket: "{{ .gitlab_registry_bucket }}"
            accesskey: "{{ .gitlab_registry_s3_access_key }}"
            secretkey: "{{ .gitlab_registry_s3_secret_key }}"
  dataFrom:
    - extract:
        key: gitlab-registry
    - extract:
        key: gitlab
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name s3cmd-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        local: |
          [gitlab-backup]
          accesskey = "{{ .gitlab_backup_s3_access_key }}"
          accesstoken = "{{ .gitlab_backup_s3_secret_key }}"
          host_base = "s3.monosense.io:9000"
          guess_mime_type = True
          [gitlab-rail]
          accesskey = "{{ .gitlab_rail_s3_access_key }}"
          accesstoken = "{{ .gitlab_rail_s3_secret_key }}"
          host_base = "s3.monosense.io:9000"
          guess_mime_type = True
          [gitlab-artifacts]
          accesskey = "{{ .gitlab_artifacts_s3_access_key }}"
          accesstoken = "{{ .gitlab_artifacts_s3_secret_key }}"
          host_base = "s3.monosense.io:9000"
          guess_mime_type = True
          [gitlab-uploads]
          accesskey = "{{ .gitlab_uploads_s3_access_key }}"
          accesstoken = "{{ .gitlab_uploads_s3_secret_key }}"
          host_base = "s3.monosense.io:9000"
          guess_mime_type = True
          [gitlab-packages]
          accesskey = "{{ .gitlab_packages_s3_access_key }}"
          accesstoken = "{{ .gitlab_packages_s3_secret_key }}"
          host_base = "s3.monosense.io:9000"
          guess_mime_type = True
  dataFrom:
    - extract:
        key: gitlab-backup
    - extract:
        key: gitlab-rail-storage
    - extract:
        key: gitlab-artifacts-storage
    - extract:
        key: gitlab-uploads-storage
    - extract:
        key: gitlab-packages-storage
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gitlab-backup-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesskey: "{{ .gitlab_backup_s3_access_key }}"
        secretkey: "{{ .gitlab_backup_s3_secret_key }}"
  dataFrom:
    - extract:
        key: gitlab-backup
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/trosvald/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &appname gitlab-saml-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *appname
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        provider: |
          name: 'saml'
          label: 'SSO'
          args:
            assertion_consumer_service_url: 'https://gitlab.monosense.io/users/auth/saml/callback'
            idp_cert_fingerprint: "{{ .gitlab_saml_cert_fingerprint }}"
            idp_sso_target_url: 'https://auth.monosense.io/application/saml/gitlab/sso/binding/redirect/'
            issuer: 'https://gitlab.monosense.io'
            name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'
            attribute_statements:
              email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress']
              first_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
              nickname: ['http://schemas.goauthentik.io/2021/02/saml/username']
  dataFrom:
    - extract:
        key: gitlab
