---
originRequest:
  originServerName: external.monosense.io

ingress:
  - hostname: monosense.io
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.monosense.io"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
